name: Main branch - Windows installer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn --batch-mode package --file pom.xml

    - name: Set up package directories
      run: mkdir target/jpack

    - name: Copy the jar
      run: cp target/zatikon-*.jar target/jpack/zatikon.jar

      # TODO: handle version number
    - name: Package into exe
      run: jpackage --type exe --name Zatikon --input target/jpack/ --main-jar zatikon.jar --main-class leo.client.WindowsLauncher --dest exepack --app-version 1.2.0 --icon src/main/resources/icons/zatikon.ico --win-dir-chooser --win-shortcut --win-menu --win-shortcut-prompt --win-upgrade-uuid 6540EFA3-65AB-4E93-920C-54793ECC7E86

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: zatikon-1.2.0-dev
        path: exepack
