name: Main branch - Linux JAR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn --batch-mode package --file pom.xml -Dlwjgl.natives=natives-linux

#    - name: Copy to staging
#      run: mkdir staging && cp target/zatikon-*.jar staging

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: zatikon-1.2.0-dev
        path: target/zatikon-*.jar

# Well it's cool it can be deployed but I don't need that now
#    - name: Publish package
#      run: mvn --batch-mode deploy
#      env:
#        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

# What I need is to create a release on Github and publish latest version on Flathub. TODO: that.
