name: Release build - Linux JAR

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Get version from tag
        id: get-version
        run: echo "version=${GH_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        env:
          GH_REF: ${{ github.ref }}

      - name: Set version in pom.xml
        run: mvn --batch-mode --file pom.xml versions:set '-DnewVersion=${{ steps.get-version.outputs.version }}'

      - name: Build with Maven
        run: mvn --batch-mode --file pom.xml package -Dlwjgl.natives=natives-linux

      - name: Generate SHA256 checksum
        run: sha256sum target/zatikon-${{ steps.get-version.outputs.version }}.jar > target/zatikon-${{ steps.get-version.outputs.version }}.sha256

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: zatikon-${{ steps.get-version.outputs.version }}
          path: target/zatikon-*.jar

# Well it's cool it can be deployed but I don't need that now
#    - name: Publish package
#      run: mvn --batch-mode deploy
#      env:
#        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

# What I need is to create a release on Github and publish latest version on Flathub. TODO: that.
